name: Generate and Publish Allure Report

on:
  workflow_dispatch:
    inputs:
      type:
        description: 'Test type to run (smoke or nightly)'
        required: true
        default: smoke
        type: choice
        options: [smoke, nightly]

permissions:
  contents: write  # needed to push to gh-pages

jobs:
  generate-report:
    runs-on: ubuntu-latest

    env:
      TEST_TYPE: ${{ inputs.type }}

    # If you later run smoke and nightly in parallel (e.g., two runs),
    # serialize deployments per type to avoid racing pushes to gh-pages/<type>.
    concurrency:
      group: gh-pages-${{ inputs.type }}
      cancel-in-progress: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        # Continue job even if tests fail
        run: |
          npm run test:${{ env.TEST_TYPE }} || true

      - name: Verify if Allure results exist
        if: success() || failure()
        run: |
          if [ -d "allure-results" ]; then
            echo "Found allure-results folder - continuing."
          else
            echo "No allure-results folder - skipping report generation."
            exit 1
          fi

      - name: Checkout gh-pages branch to get previous history (for this type only)
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
        continue-on-error: true

      - name: Generate Allure Report with History (scoped to type)
        # pin commit hash for security (v1.13)
        uses: simple-elf/allure-report-action@53ebb757a2097edc77c53ecef4d454fc2f2f774c
        with:
          # Current run inputs/outputs
          allure_results: allure-results
          allure_report: allure-report

          # Roots
          gh_pages: gh-pages
          allure_history: allure-history

          # Make the action generate links under /<type>/...
          subfolder: ${{ env.TEST_TYPE }}
          
          # Dynamic title e.g. "Smoke – 2025-10-23"
          report_name: "${{ env.TEST_TYPE == 'smoke' && 'Smoke' || 'Nightly' }} - ${{ steps.date.outputs.today }}"

          # Keep only the last 20 reports per subfolder
          keep_reports: 20

      - name: Deploy to GitHub Pages (to /<type>)
        # pin commit hash for security (v4.0.0)
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages

          # Publish the WHOLE allure-history root; it already contains /smoke and /nightly
          publish_dir: allure-history
